### ISSUE TITLE
Cordova iOS: TypeError: null is not an object (evaluating 'matches[1]')

### ISSUE THREAD

**Issue by jakecarlson** [quavedev/accounts-apple#3]
Everything seems to work very well in the browser -- so I think the service is configured properly. However, it hangs in my iOS app when the user initiates the login by tapping the Sign In with Apple button. Xcode doesn't report any errors, but the Safari console reports the following error:

TypeError: null is not an object (evaluating 'matches[1]') on namespace.js:6

I can't seem to find any further information about this error.

I'm using Xcode 12.2 and Meteor Meteor 1.11.1. Any thoughts or troubleshooting tips?

**Comment by renanccastro** [comment]
Hello! I've released a new version that fixes this, are you up to date?

quave:accounts-apple@1.1.3
quave:apple-oauth@1.4.2

**Comment by jakecarlson** [comment]
Ah you are absolutely correct. Not sure how I got an old version. I updated and am no longer having issues. Thanks for all the great work on this package!
