### ISSUE TITLE
Upgrade to Meteor 3.0

### ISSUE THREAD

**Issue by derwaldgeist** [quavedev/accounts-apple#5]
As suggested by Filipe, here's my upgrade request for Meteor 3.0. Would be cool if you could support this package on the new release. Thanks!

**Comment by renanc-br** [comment]
Hi @derwaldgeist . Meteor v3 alpha is supported in version 4.0.0-beta onwards.

Please refer to this branch to the changes needed: https://github.com/quavedev/apple-oauth/tree/meteor-v3.x
It's only 1 small change to the way serviceConfiguration is initialized, it's now async.

quave:accounts-apple@4.0.0-beta and quave:apple-oauth@4.0.0-beta

Please test it and let us know how it goes.

---
# EDIT

There is still some more work to do. updateOrCreateUserFromExternalService has not migrated yet, we are blocked waiting on this PR: updateOrCreateUserFromExternalService.

**Comment by carlosalvidrez** [comment]
Hi there! Hoping this can be modernized for Meteor 3.0.0-rc.4. 
Thanks!

**Comment by renanccastro** [comment]
published v4 with meteor v3 support
